services:
  - type: web
    name: liberty-nordic-dashboard
    env: go
    buildCommand: go mod tidy && go build -o liberty-nordic-dashboard
    startCommand: ./liberty-nordic-dashboard
    envVars:
      - key: PORT
        value: 8080 